## Feature Engineering.

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('SampleFile.csv')
df.head()

   LotArea  MSSubClass
0     8450          60
1     9600          20
2    11250          60
3     9550          70
4    14260          60

#### Absolute Maximum Scaling

In [6]:
max_abs = np.max(np.abs(df), axis = 0)  # axis = 0 for calculating maximum
#absolute value for each column.

scaled_df = df/max_abs
scaled_df.tail()

       LotArea  MSSubClass
1455  0.036781    0.315789
1456  0.061209    0.105263
1457  0.042008    0.368421
1458  0.045144    0.105263
1459  0.046166    0.105263

#### Min-max Scaling

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
print(type(scaled_data))
scaled_df = pd.DataFrame(scaled_data, columns = df.columns)
print(type(scaled_df))


scaled_df.head()

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>

    LotArea  MSSubClass
0  0.033420    0.235294
1  0.038795    0.000000
2  0.046507    0.235294
3  0.038561    0.294118
4  0.060576    0.235294

#### Normalization (vector normalization)

In [6]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns = df.columns)

scaled_df.head()

    LotArea  MSSubClass
0  0.999975    0.007100
1  0.999998    0.002083
2  0.999986    0.005333
3  0.999973    0.007330
4  0.999991    0.004208

#### Standardization

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns = df.columns)

scaled_df.head()

    LotArea  MSSubClass
0 -0.207142    0.073375
1 -0.091886   -0.872563
2  0.073480    0.073375
3 -0.096897    0.309859
4  0.375148    0.073375

#### Robust Scaling

In [8]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns = df.columns)

scaled_df.head()

    LotArea  MSSubClass
0 -0.254076         0.2
1  0.030015        -0.6
2  0.437624         0.2
3  0.017663         0.4
4  1.181201         0.2